server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
spring:
  profiles:
    #    active: development
    active: local
  mvc:
    dispatch-options-request: true
  servlet:
    multipart:
      enabled: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    groups-order: DESC
  show-actuator: true
